# Your name and what you do
name: Cesar Chavez
bio: Smart Contract Developer | mStable

description: Cesar Chavez's Personal Website

# Profile picture
picture: assets/images/profile_.jpg
 
url: https://doncesarts.github.io

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
#twitter: doncesarts
linkedin: christopher-césar-chávez-lópez-27566b12
github: doncesarts
email: doncesarts@gmail.com
cv: assets/cv-dapp.pdf
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - <b>Languages </b> JavaScript, Java, Solidity, HTML, Typescript
    - <b>Web </b>  NodeJs, React, Redux, Jest, Enzyme, Web Design Systems, GraphQL.
    - <b>Web3</b>  Web3.js, Ethers Truffle, Hardhat, Ganache, Metamask
    - <b>Databases</b>  Oracle, MySQL, Mongo DB
    - <b>Servers</b>  Apache Tomcat, WebLogic, WebSphere Application Server
    # - <b>Frameworks</b>  Struts, JSF, Spring, Spring MVC, Hibernate, JPA


# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    React-Dapp-ERC721-Token:
        name: React Dapp - ERC721 Decentralized Art Market
        description: React Dapp Decentralized ERC721 Tokens Market Place
        url: https://github.com/doncesarts/react-dapp-erc721-token
        tags: React, Truffle, Web3.js, Solidity
    React-Dapp-ERC720-Token:
        name: React Dapp - ERC20 Token for an ICO
        description: React Dapp that enables to create an Initial Coin Offering of an ERC20 Token
        url: https://github.com/doncesarts/react-dapp-erc20-token
        tags: React, Truffle, Web3.js, Solidity
    Nextjs-Dapp-ERC721-Token:
        name: Nextjs Dapp - ERC721 Decentralized NFT Market 
        description: NFT Market  Market pkace - NextJs Dapp that allows the exchange of ERC721 tokens Polygon Matic
        url: https://github.com/doncesarts/nextjs-dapp-matic-nft  
        tags: Nextjs, Hardhat, Ethers.js, Solidity, Polygon    
# do you want to display a badges section? true or false
badges: true

# add your badges here
badge-list:
    Ethereum-Bootcamp-Udemy:
        name: Ethereum Blockchain Developer Bootcamp With Solidity (2021)
        organization: Udemy
        url: https://udemy-certificate.s3.amazonaws.com/image/UC-bfbb4b81-b372-4e47-9043-a155557f1a1a.jpg
    IBM-Blockchain-Essentials-V2:
        name: IBM Blockchain Essentials V2
        organization: IBM
        url: https://www.credly.com/badges/d4d2334b-f5e6-4525-9b8a-6d75564f7bdd       
    IBM-Blockchain-Foundation-Developer-V2:
        name: IBM Blockchain Foundation Developer V2
        organization: IBM
        url: https://www.youracclaim.com/badges/1f065694-b2f0-4c41-aa74-df98cf218612



# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
